### PR TITLE
fix #2812 with isSubmitting

### LINKED ISSUE #2812: Strange async submit bug introduced on 6.5.0
Hi!

On my app I identified a bug where "isSubmitting" doesn't respect async functions on submitting form.

I will later identify where exactly this is happening to create a proper CodeSandBox repro.

But I couldn't so far... Async examples here are working fine.
I know this is on 6.5.0 because I was testing each version to find the one that breaks the behavior.

May I raise this issue til I figure out how to reproduce this?

This still happens on latest version

Version 6.4.1 with correct behavior
rhf 6-4-1

Version 6.5.0
rhf 6-5-0

### PR DESCRIPTION
**Pull request by bluebill1049**
fix #2812

https://codesandbox.io/s/happy-grass-xij0y?file=/src/src/useForm.ts

### CODE REVIEW

File: src/useForm.ts [hunk 1]
```diff
@@ -1050,6 +1050,7 @@ export function useForm<
         ) {
           updateFormState({
             errors: {},
+            isSubmitting: true,
```
Comment (JeromeDeLeon) [inline src/useForm.ts:1053]: Hmm 🤔 so we are repeating this value to avoid bring replaced by it's previous one?

Comment (JeromeDeLeon) [reply src/useForm.ts:1053]: Shouldn't we just use the previous value from `setFormState` instead?

Comment (bluebill1049) [reply src/useForm.ts:1053]: this is because we are reading the value from the `ref` with Proxy, so the other way to fix it is `formStateRef.isSubmitting = true`, but this is one situation when we invoke updateFormState 3 times in a row. it's fine to bring another callback to the `updateState` for `prevState`, but I think it's a overkill unless we can find another scenario which we need it.

Comment (JeromeDeLeon) [reply src/useForm.ts:1053]: Oh yeah, seems good to me. We will have one more source of truth if we add that prevState 😆 my bad.

**Review by JeromeDeLeon — APPROVED** [review]

File: src/useForm.ts (hunk 1 above)
Comment (bluebill1049) [reply src/useForm.ts:1053]: thanks for the review! @JeromeDeLeon
