### PR TITLE
🐞 fix: prevent useWatch re-render when unrelated field validation is …

### LINKED ISSUE #12925: issue: useWatch is triggered when unrelated field validation is triggered
### Version Number

7.59.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/awesome-bush-v3snlv

### Steps to reproduce

1. Go to codesandbox
2. Open browser dev console
3. Type into form's input field
4. See how _ComponentWatchingOrganization rendering_ is printed even though that component is using useWatch to watch `organization` which is never updated. The `MyInput` component only updates `firstName` and triggers validation for `secondName` using the `rules`.

### Expected behaviour

I expect ComponentWatchingOrganization not to render because it uses useWatch to watch totally unrelated field in the form. This issue does not exist in v7.54.2.

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by cyky**
### Description

Fixes #12925

`useWatch` subscribers re-render when unrelated field validation is triggered via `rules.deps`. This is a regression since v7.55.0 when `_subjects.values` and `_subjects.state` were merged.

### Root cause

In `shouldRenderFormState`, the condition `Object.keys(formState).length >= Object.keys(_proxyFormState).length` acts as a short-circuit that bypasses key-matching. When `trigger()` emits `{ errors: {} }` (1 key) and `useWatch` subscribes with `{ values: true }` (1 key), `1 >= 1` passes despite zero key overlap.

### Changes

- **`shouldRenderFormState.ts`**: Guard the size-based condition with `isRoot` so it only applies to the root `useForm` subscriber. Non-root subscribers now rely on actual key overlap matching.
- **`getProxyFormState.ts`**: `defaultValues` was set as a plain property instead of a tracked getter, so `useFormState` accessing `defaultValues` never registered a subscription. This was masked by the size-based condition but is now properly tracked.
- **Test updates**: Adjusted render count assertions that included spurious re-renders caused by the bug

### CODE REVIEW

File: src/logic/getProxyFormState.ts [hunk 1]
```diff
@@ -30,5 +28,19 @@ export default <
...
+        if (control._proxyFormState.defaultValues !== VALIDATION_MODE.all) {
+          control._proxyFormState.defaultValues =
+            !isRoot || VALIDATION_MODE.all;
+        }
+
+        localProxyFormState && (localProxyFormState.defaultValues = true);
+        return control._defaultValues;
+      },
+    });
+  }
```
Comment (bluebill1049) [inline src/logic/getProxyFormState.ts]: what's this for?

Comment (cyky) [reply src/logic/getProxyFormState.ts]: The `defaultValues` isn't being passed with the `formState`object here. Without this the useFormState cant subscribe to defaultValues changes. This was being previously masked by the size-based short-circuit in the `shouldRenderFormState`.

There is existing test `formState.defaultValues and useFormState().defaultValues should be equal after reset` that fails without this change.

We could probably include the default values with the formState but I'm not sure if that is better approach?

Comment (cyky) [reply src/logic/getProxyFormState.ts]: Actually I went ahead and removed this and refactored the `useFormState` to include the `defaultValues`.

Let me know if this is better approach.

**Review by bluebill1049 — APPROVED** [review]
