### PR TITLE
Fix undefined ref in options

### LINKED ISSUE #1718: Error in dynamic radio group options + calling setValue
**Describe the bug**
I have a radio group. The number of options are dynamic based on conditions. In my code, after alternating between options twice I get an error when trying to use `setValue`. In the code sandbox this will happen after 7 alternations.
I noticed the error does not occur if I do not use `setValue` and it appears the `field.options` keep growing in size with each change.

**To Reproduce**
1. Go to https://codesandbox.io/s/empty-tree-qff1x?file=/src/App.js
2. Alternate clicking between `Button 1` and `Button 2`
3. After 7 times you will see an error

**Codesandbox link (Required)**
https://codesandbox.io/s/empty-tree-qff1x?file=/src/App.js

**Desktop (please complete the following information):**
 - OS: Mac OSx
 - Browser Chrome, Firefox, Safari

### PR DESCRIPTION
**Pull request by JeromeDeLeon**
Fix #1718

@bluebill1049 , At first I put the `filter` to `setFieldValue` function but resulted in below image
Screenshot from 2020-05-29 12-43-49

then I tried to move it to `registerFieldsRef` function instead and resulted in below image:
Screenshot from 2020-05-29 12-52-10

### CODE REVIEW

**Comment by bluebill1049** [comment]
wow, thanks so much for picking this up @JeromeDeLeon

File: src/useForm.ts [hunk 1]
```diff
@@ -897,7 +897,7 @@ export function useForm<
       field = isRadioOrCheckbox
         ? {
             options: [
-              ...((field && field.options) || []),
+              ...((field && field.options.filter(Boolean)) || []),
```
Comment (bluebill1049) [inline src/useForm.ts:900]: by the way, i belive we have `unique`

Comment (JeromeDeLeon) [reply src/useForm.ts:900]: I will try to look into that. I'm currently testing it to see if I could remove the `[empty x 3, {...}, {...}]` to make it `[{...}, {...}]` because right now I'm still seeing it even though I used `filter`

**Comment by JeromeDeLeon** [comment]
@bluebill1049 , Could you take a look at why E2E test failed? seems to be related to error in connection.

**Comment by bluebill1049** [comment]
> @bluebill1049 , Could you take a look at why E2E test failed? seems to be related to error in connection.

Thanks @JeromeDeLeon i will take this over and sort out over the weekend. 🙏
