### PR TITLE
fix/improve setError & clearError

### LINKED ISSUE #1908: Inconsistent behavior of setError
**Describe the bug**
Calling `setError` fn on submit cause doesn't work correctly.
https://codesandbox.io/s/react-hook-form-set-error-clear-error-qdio6?file=/src/index.js

To reproduce the bug:
1. Go to https://codesandbox.io/s/react-hook-form-set-error-clear-error-qdio6?file=/src/index.js
2. Click on `Submit` button.
3. Enter 2+ chars in the `username` input field.
Error disappeared.
4. Enter 2+ chars in the `lastname` input field.
Error remained.

What is the correct behavior?

### PR DESCRIPTION
**Pull request by bluebill1049**
### setError

`setError` will focus one error at a time and remove confusing set multiple errors, behavior change.

- `setError` will persis an error if it's not part of the form, which requires manual remove with `clearError`
- `setError` error will be removed by validation rules, rules always take over errors

**Reason**

should focus an error at a time just like the name suggested, refine the API and remove multiple errors set.

``` diff
- setError('test', 'test', 'test')
+ setErrror('test', { type: 'test, message: 'bill'})
```

----

### clearError

Rename to `clearErrors`

**Reason**

This function allow remove multiple errors, so make sense to rename it to clearErrors

``` diff
- clearError()
+ clearErrors()
```

fix https://github.com/react-hook-form/react-hook-form/issues/1908

### CODE REVIEW

**Comment by JeromeDeLeon** [comment]
I think we could go back to this and `setValue` when users wanted `setValues` and `setErrors` to be implemented without the cause of extra re-renders, but I think it's fine for to make consistency around the API. :+1:

**Comment by bluebill1049** [comment]
> I think we could go back to this and `setValue` when users wanted `setValues` and `setErrors` to be implemented without the cause of extra re-renders, but I think it's fine for to make consistency around the API. 👍

Totally agree, otherwise the API name is very confusing against its functionality. 

`['xxx', 'tss'].map(setError)` should do the job

if users complains about the multiple re-render, we can then consider introducing setValues setErrors, ideally to avoid.

File: src/types/form.ts [hunk 1]
```diff
@@ -336,14 +335,18 @@ export type UseFormMethods<TFieldValues extends FieldValues = FieldValues> = {
...
   setError(
     name: FieldName<TFieldValues>,
-    type: string,
-    message?: Message,
+    error:
+      | {
+          types: MultipleFieldErrors;
+        }
+      | {
+          message?: Message;
```
Comment (JeromeDeLeon) [inline src/types/form.ts:345]: curious tho why is it message is not required?

Comment (bluebill1049) [reply src/types/form.ts:345]: just like `register({ required: true })`

File: src/useForm.ts [hunk 2]
```diff
@@ -665,39 +663,23 @@ export function useForm<
...
-              type: '',
-            }
-          : {
-              type,
-              message,
-            }),
-        shouldRender: true,
-      });
-    }
+    setInternalError({
```
Comment (keiya01) [inline src/useForm.ts:677]: `setInternalError` method is used inside only `setError` method.  I think you can expand `setInternalError` method to `setError` method.

File: src/types/form.ts (hunk 1 above)
Comment (JeromeDeLeon) [reply src/types/form.ts:345]: Ahh make sense. :laughing:

File: src/useForm.ts [hunk 3]
```diff
@@ -665,39 +663,23 @@ export function useForm<
...
-    type: string | MultipleFieldErrors = '',
-    message?: Message,
+    error:
+      | {
+          types: MultipleFieldErrors;
+        }
+      | {
+          message?: Message;
+          type: string;
+        },
```
Comment (JeromeDeLeon) [inline src/useForm.ts:673]: could we create type ErrorOption or Error to reduce redundancy in type?

Comment (bluebill1049) [reply src/useForm.ts:673]: sounds good to me 👍

Comment (bluebill1049) [reply src/useForm.ts:673]: will do that after work :)

Comment (JeromeDeLeon) [reply src/useForm.ts:673]: I could do it for you. :D

File: src/logic/shouldRenderBasedOnError.ts [hunk 4]
```diff
@@ -28,10 +28,7 @@ export default function shouldRenderBasedOnError<
   const currentFieldError = get(error, name);
```
Comment (keiya01) [inline src/logic/shouldRenderBasedOnError.ts:28]: `isManual` is used inside unit test. I think you had better remove this variables from unit test.

**Review by keiya01 — COMMENTED** [review]
I'm sorry for the delay in my review🙏

File: src/useForm.ts (hunk 2 above)
Comment (bluebill1049) [reply src/useForm.ts:677]: oh man! totally!

File: src/useForm.ts (hunk 3 above)
Comment (bluebill1049) [reply src/useForm.ts:673]: commit please! 💋

**Comment by JeromeDeLeon** [comment]
Haha you got me first @bluebill1049

**Comment by bluebill1049** [comment]
> Haha you got me first @bluebill1049

Thanks for your help @JeromeDeLeon 🙏

**Comment by JeromeDeLeon** [comment]
Nah. It was nothing compared to you. My laptop stopped responding when I was about to test locally 🤯🤯

File: src/useForm.ts (hunk 2 above)
Comment (JeromeDeLeon) [reply src/useForm.ts]: Man! didn't notice it before! :laughing:

File: src/useForm.ts (hunk 3 above)
Comment (bluebill1049) [reply src/useForm.ts]: Screen Shot 2020-06-19 at 3 16 27 pm

first-time see 8 in months...

File: src/useForm.ts (hunk 2 above)
Comment (bluebill1049) [reply src/useForm.ts]: Thanks @keiya01 
image

we are 8 again. lol

Comment (bluebill1049) [reply src/useForm.ts]: I miss when the lib was `2k` tho lol

File: src/useForm.ts [hunk 5]
```diff
@@ -629,48 +627,15 @@ export function useForm<
...
-        ref: fieldsRef.current[name] ? fieldsRef.current[name]!.ref : {},
-      });
-
-      if (shouldRender) {
-        reRender();
-      }
-    }
-  };
-
   function setError(name: FieldName<TFieldValues>, error: ErrorOption): void {
```
Comment (keiya01) [inline src/useForm.ts:630]: very nice!

**Review by keiya01 — COMMENTED** [review]
It's nice to have less code :)

File: src/useForm.ts (hunk 2 above)
Comment (JeromeDeLeon) [reply src/useForm.ts]: It just means it becoming useful to others because they want to stick with it and push some new features to us. :smile:

**Comment by bluebill1049** [comment]
@keiya01 @JeromeDeLeon happy to approve?

**Review by JeromeDeLeon — APPROVED** [review]

**Comment by bluebill1049** [comment]
Thanks guys for the review.

**Comment by 2DSharp** [comment]
I think that would make things clearer, thanks @bluebill1049

File: src/useForm.ts [hunk 6]
```diff
@@ -1004,12 +942,20 @@ export function useForm<
...
+          Object.keys(errorsRef.current).every((name) =>
+            Object.keys(fieldsRef.current).includes(name),
+          )
+        ) {
           errorsRef.current = {};
           reRender();
           await callback(transformToNestObject(fieldValues), e);
         } else {
-          errorsRef.current = fieldErrors;
+          errorsRef.current = {
```
Comment (AEPKILL) [inline src/useForm.ts:955]: why need to merge the old error state?
