### PR TITLE
Revert "✨  Add support for generic components using `FieldPathWithVal…

### LINKED ISSUE #6679: [Bug]: Regression: TS2589: Type instantiation is excessively deep and possibly infinite
### Version Number

7.16.2

### Codesandbox/Expo snack

Codesandbox still doesn't allow me to install the latest version

### Steps to reproduce

1. Upgrade from 7.16.1 to 7.16.2, no other changes
2. Cue error

### Expected behaviour

TypeScript compilation should succeed without any warnings.
I believe #6658 is the cause of introducing this error, this is a regression of #4441

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by bluebill1049**
…ue` (#6562)"

This reverts commit f5a25199c27b4b0622556ca634cd869b271117eb.

fix #6679

### CODE REVIEW

File: src/useController.ts [hunk 1]
```diff
@@ -18,14 +18,10 @@ import { useSubscribe } from './useSubscribe';
 
 export function useController<
   TFieldValues extends FieldValues = FieldValues,
-  TResult = any,
-  TName extends FieldPathWithValue<TFieldValues, TResult> = FieldPathWithValue<
```
Comment (bluebill1049) [inline src/useController.ts:22]: this is the point of failure with codesandbox CRA
