### PR TITLE
🐞 fix: respect parent-provided useFieldArray rules (#13082)

### LINKED ISSUE #13082: issue: Regression useFieldArray rule attribute not being respected when passed from parent
### Version Number

7.64.0

### Codesandbox/Expo snack

https://codesandbox.io/p/devbox/react-hook-form-usefieldarray-rules-forked-9lgp8m?workspaceId=ws_SpFfrNeSXw3k7QXR2peBdn

### Steps to reproduce

 I am upgrading from 7.52.1 to 7.63.0 (also verified regression with 7.64.0) and I have an existing scenario that is now broken:

1. Go to [this codesandbox](https://codesandbox.io/p/devbox/react-hook-form-usefieldarray-rules-forked-9lgp8m?workspaceId=ws_SpFfrNeSXw3k7QXR2peBdn)
2. Either delete all field-rows or append until 4 is reached then delete one to make the form invalid
3. Click submit
4. Console will log "validSubmit" (first param in handleSubmit)

### Expected behaviour

onInvalidSubmit should be called as the form does not pass the rules provided by the parent.

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Han5991**
⏺ Summary

  fixes #13082 

  Problem

  When rules were passed to useFieldArray from a parent component, they were wrapped in React.useMemo without proper dependencies, causing the rules to be registered only once during initial render. If the rules object reference changed (e.g., created inline or from useMemo in parent), the validation would not update
  properly.

  Solution

  - Removed unnecessary React.useMemo wrapper around the control.register call in src/useFieldArray.ts:112-118

  Changes

  - src/useFieldArray.ts: Simplified rules registration by removing useMemo wrapper
  - src/tests/useFieldArray.test.tsx: Added comprehensive test case validating that rules from parent component are properly enforced

### CODE REVIEW

File: src/useFieldArray.ts [hunk 1]
```diff
@@ -109,15 +109,11 @@ export function useFieldArray<
...
-        name as FieldPath<TFieldValues>,
-        rules as RegisterOptions<TFieldValues>,
-      ),
-    [control, rules, name],
-  );
+  rules &&
+    (control as Control<TFieldValues, any, TTransformedValues>).register(
+      name as FieldPath<TFieldValues>,
+      rules as RegisterOptions<TFieldValues>,
+    );
```
Comment (bluebill1049) [inline src/useFieldArray.ts]: could we try to use rules with ref instead? would be good if we can still keep the memo.

```tsx
const rulesRef = useRef(rules)

reulsRef.current = rules
```

**Review by bluebill1049 — COMMENTED** [review]
thanks for the PR!

File: src/useFieldArray.ts (hunk 1 above)
Comment (Han5991) [reply src/useFieldArray.ts]:
```tsx
  const rulesRef = React.useRef(rules);

  rulesRef.current = rules;

  control._names.array.add(name);

  rulesRef.current &&
    (control as Control<TFieldValues, any, TTransformedValues>).register(
      name as FieldPath<TFieldValues>,
      rulesRef.current as RegisterOptions<TFieldValues>,
    );
```
`rulesRef` as suggested. This keeps the latest `rules` value in a ref while preserving memoization. Test passes. Does this look right?

Comment (bluebill1049) [reply src/useFieldArray.ts]:
```tsx
const rulesRef = React.useRef(rules);

  rulesRef.current = rules;

  const _actioned = React.useRef(false);

  control._names.array.add(name);

  React.useMemo(
    () =>
      rules &&
      (control as Control<TFieldValues, any, TTransformedValues>).register(
        name as FieldPath<TFieldValues>,
        rulesRef.current as RegisterOptions<TFieldValues>,
      ),
    [control, name],
  );
  ```
  
  what about this?

Comment (Han5991) [reply src/useFieldArray.ts]: image

re-ran the test suite, but it still fails.

Comment (Han5991) [reply src/useFieldArray.ts]: image

```tsx
  React.useMemo(
    () =>
      rules &&
      (control as Control<TFieldValues, any, TTransformedValues>).register(
        name as FieldPath<TFieldValues>,
        rules as RegisterOptions<TFieldValues>,
      ),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [control, name, fields.length, rules],
  );
```
What do you think about this code?

**Review by bluebill1049 — APPROVED** [review]
ty very much for the fix
