### PR TITLE
Fixing key

### LINKED ISSUE #351: Help: Typescript errors support for field arrays
**Describe the bug**
I have a form in which I dynamically create field arrays (as in the examples). 
Therefore I have the following Typescript interface:

```typescript
export interface ICostInformationFormValues {
  rentalCost: number;
  additionalCost: Array<{ name: string; value: number }>;
}
```

I want to display validation errors for the dynamically generated fields and that's the problem. The field arrays are handled differently in the errors than in for example getValues({ nested: true }). 
Instead of using my Typescript interface, the Field Array error messages are stored with the index of the field name (e.g.: "additionalCost[1][value]"). 

When I try to read the errors for this field:
```typescript
errors["additionalCost[1][value]"]
```

 I get the following Typescript error message:
```typescript
Element implicitly has an 'any' type because expression of type '"additionalCost[1][value]"' can't be used to index type 'Partial<Record<"rentalCost" | "additionalCost", FieldError>>'.
  Property 'additionalCost[1][value]' does not exist on type 'Partial<Record<"rentalCost" | "additionalCost", FieldError>>'.
```

When I simply log the errors value to my console I can see the error messages for the array fields. I just can't read them with Typescript support.

**Expected behavior**
I would expect to be able to read the error messages based on my Typescript interface like I read the errors for every other field. 

```typescript
errors.additionalCost[1]["value"].message
```

**Additional context**
I'm using [Material-UI ](https://material-ui.com) to create my textfields.
If you need more context please let me know.

Thanks for your help :)
Daniel

### PR DESCRIPTION
**Pull request by stramel**
Abstracts the `FieldName` and `FieldValue` out of generics into types.

This also utilizes the `Extract` helper that pulls out only the `string` keys.

There is still a bit of clean up left in here. Tried to tackle some things as I saw them.

Should resolve #351

### CODE REVIEW

File: src/types.ts [hunk 1]
```diff
@@ -93,11 +99,11 @@ export interface Field extends ValidationOptions {
 }
 
 export type FieldsRefs<Data extends FieldValues> = Partial<
```
Comment (barrymay) [inline src/types.ts]: (sorry I know I've been lacking on my assistance lately, but I do want to help ;) )

since you removed Data in 23, does FormValues fit here too?  Would love to get rid of Data as a type name since it's kinda meaningless

File: src/contextTypes.ts [hunk 2]
```diff
@@ -1,28 +1,24 @@
 import * as React from 'react';
 import {
   FieldValues,
+  FieldName,
```
Comment (barrymay) [inline src/contextTypes.ts]: I love the complexity reduction be importing this in :)

**Review by barrymay — APPROVED** [review]
since this is such a huge change, I'll take a test run of this once it's in a beta build - otherwise I would helpfully trust the unit tests :)

**Comment by bluebill1049** [comment]
thanks very much @stramel and @barrymay 's code review 👍

**Comment by bluebill1049** [comment]
This Pika CI is no longer working for some reason...

**Comment by barrymay** [comment]
I test from latest master and let you know

**Comment by bluebill1049** [comment]
thanks @barrymay i will merge this and publish a beta version soon.

**Comment by bluebill1049** [comment]
`react-hook-form@3.23.19-beta.3` here is the beta version @barrymay @stramel

**Comment by barrymay** [comment]
Tested the beta locally - looks good :)

**Comment by bluebill1049** [comment]
awesome thanks @barrymay

**Comment by bluebill1049** [comment]
tested on my end as well. looks good. going to release the patch this weekend.
