### PR TITLE
close #2073

### LINKED ISSUE #2073: Types lost in version 6
**Describe the bug**
Not sure why, but there is bunch of TS types missing after I upgraded to version 6.

**To Reproduce**
This import line `import { FieldError } from 'react-hook-form'` produces:
> Module '"../../../node_modules/react-hook-form/dist"' has no exported member 'FieldError'.  TS2305

**Codesandbox link (Required)**
https://codesandbox.io/s/nervous-joliot-y1qnj?file=/src/App.tsx

**Expected behavior**
I would expect that everything from `node_modules/react-hook-form/dist/types/form.d.ts` would be ready to use. Turns out only certain types are exported: https://github.com/react-hook-form/react-hook-form/blob/master/src/types/index.ts

**Screenshots**
Screenshot 2020-07-05 at 14 41 33

**Desktop (please complete the following information):**
 - react-hook-form 6.0.1
 - TypeScript 3.9.4
 - Node v12.16.3
 - npm 6.14.4
- yarn 1.22.4
- MacOs 10.15.5

### PR DESCRIPTION
**Pull request by bluebill1049**
expose the following types:

```
Error
UseFormOptions,
UseFieldArrayOptions,
Field,
Mode,
```

### CODE REVIEW

File: src/types/form.ts [hunk 1]
```diff
@@ -129,20 +129,13 @@ export type ValidationRules = Partial<{
 
 export type MultipleFieldErrors = Record<string, ValidateResult>;
 
-export type FieldError = {
+export type Error = {
```
Comment (kotarella1110) [inline src/types/form.ts:132]: @bluebill1049 Why did you rename `FieldError` to `Error`? Shouldn't we just prefix "Field" like `FieldErrors`, `FieldValues`, `FieldValue`, etc?

Comment (bluebill1049) [reply src/types/form.ts:132]: I was trying to reflect on our `errors` object, happy to keep it as `FieldError` tho.
