### PR TITLE
close #369 remove react native type

### LINKED ISSUE #369: Typescript build failing because of 'react-native' import
**Describe the bug**
After upgrading to `3.24.0` our Typescript build is failing. This is caused by the typings importing `'react-native'`, which we're not using in our project.

```
ERROR in [at-loader] ./node_modules/react-hook-form/dist/types.d.ts:2:30
    TS2307: Cannot find module 'react-native'.

ERROR in [at-loader] ./node_modules/react-hook-form/dist/useForm.d.ts:2:30
    TS2307: Cannot find module 'react-native'.
```

**To Reproduce**
I'm assuming this happens for every Typescript based project that doesn't use `'react-native'`.

**Expected behavior**
The package should not have a dependency on `'react-native'`.

### PR DESCRIPTION
**Pull request by bluebill1049**
Just a place holder for now, if it is an issue we will remove react-native types for now

### CODE REVIEW

File: src/types.ts [hunk 1]
```diff
@@ -26,7 +25,7 @@ type Mode = keyof ValidationMode;
 
 export type OnSubmit<FormValues extends FieldValues> = (
   data: FormValues,
-  e: React.SyntheticEvent | ReactNative.GestureResponderEvent,
+  e: React.SyntheticEvent | any,
```
Comment (JeromeDeLeon) [inline src/types.ts]: Not a fun of `any` because basically telling that you don't care what type it receives. If you put `any` there, might as well remove the `React.SyntheticEvent`. Is there any reason why you remove this types? 😄

Comment (JeromeDeLeon) [reply src/types.ts]: Sorry, I just read the PR and seems like it was more like an issue regarding the use case of typescript on the web requiring to install its type dependency on react-native.

File: src/types.ts [hunk 2]
```diff
@@ -26,7 +25,7 @@ type Mode = keyof ValidationMode;
 
 export type OnSubmit<FormValues extends FieldValues> = (
   data: FormValues,
-  e: React.SyntheticEvent | ReactNative.GestureResponderEvent,
```
Comment (barrymay) [inline src/types.ts]: Let's put a //TODO comment in both places here to explain that the any is purposely there to replace ReactNative.GestureResponderEvent - that way this is easy to find

**Review by barrymay — DISMISSED** [review]
I strongly recommend the TODO comments there to make followup easy, but otherwise this is good to go.

File: src/types.ts (hunk 1 above)
Comment (stramel) [inline src/types.ts]: `| any` 😨

Comment (bluebill1049) [reply src/types.ts]: sad face :(

**Comment by bluebill1049** [comment]
I will leave a todo there and release this for now so it impacts fewer projects.

File: src/types.ts (hunk 1 above)
Comment (bluebill1049) [reply src/types.ts]: it's probably too harsh to ask people to turn on `skipLibCheck`

File: src/types.ts (hunk 2 above)
Comment (bluebill1049) [reply src/types.ts]: will do thanks.

File: src/types.ts (hunk 1 above)
Comment (bluebill1049) [reply src/types.ts]: due to this issue: https://github.com/react-hook-form/react-hook-form/issues/369

**Comment by bluebill1049** [comment]
let me know it's ready to be merged :) and we will release it <3

**Comment by bluebill1049** [comment]
@barrymay you want to merge your fix as well for the release?

**Comment by barrymay** [comment]
@bluebill1049 can we create a beta with this my last commit as a basis?  This should make it work just fine for both cases, since both frameworks inherit from BaseSyntheticEvent

File: src/types.ts [hunk 3]
```diff
@@ -25,8 +25,7 @@ type Mode = keyof ValidationMode;
 
 export type OnSubmit<FormValues extends FieldValues> = (
   data: FormValues,
-  // todo: #369 reported error in ts build while skipLibCheck isn't set to true
-  e: React.SyntheticEvent | any,
+  e: React.BaseSyntheticEvent,
```
Comment (bluebill1049) [inline src/types.ts]: 👀

Comment (bluebill1049) [reply src/types.ts]: I guess this will work for react native as well 👍

**Comment by barrymay** [comment]
> @barrymay you want to merge your fix as well for the release?

I do, since it allow for consistent usage with react-native and doesn't cause further issues.

If I have time, I want to investigate create a react-native target package, but this case should be fine for both scenarios for now.

**Comment by bluebill1049** [comment]
`3.24.1-beta.3`

**Comment by bluebill1049** [comment]
thanks @barrymay

**Review by barrymay — APPROVED** [review]
I'm fine with this change if we can leverage BaseSyntheticEvent to avoid the any.  A beta test for this is worthwhile

**Comment by bluebill1049** [comment]
> I'm fine with this change if we can leverage BaseSyntheticEvent to avoid the any. A beta test for this is worthwhile

sounds good to me!

**Comment by barrymay** [comment]
ok - so two things (@stramel I'd like your feedback on this also)

1) Bill, Can we get another beta with my other PR in it (that should be fine regardless of what we decide here)
2) If we go with BaseSyntheticEvent, it causes a slight typing problem if you use the event property in TS

if you call ```handleSubmit(onSubmit)``` as well

ANY you want to use the e for the event with specific properties of SyntheticEvent, then you need to do the following

```
 const onSubmit = (target: any, e: BaseSyntheticEvent) => {
    const x: SyntheticEvent = e as SyntheticEvent;
}
```
because SyntheticEvent is a subtype of BaseSyntheticEvent, you can just assign it to e, but an as is perfectly safe here.

We can accept this or go with the `| any` case, which makes it easier to use, but it less type safe.

I'll go with whatever you guys decide. (personally the BaseSyntheticEvent has more meaning IMO)

File: src/types.ts (hunk 3 above)
Comment (barrymay) [reply src/types.ts]: exactly - the GestureResponderEvent also inherits from BaseSyntheticEvent

**Comment by bluebill1049** [comment]
@barrymay happy to go with what u suggested.

**Comment by bluebill1049** [comment]
@stramel you happy with this?

**Comment by stramel** [comment]
Seems okay, haven't had much time to look into it.

**Review by stramel — APPROVED** [review]

**Comment by bluebill1049** [comment]
ok thanks @stramel let's take a look this again if other users report issue
