### PR TITLE
fix #5839 issue with null type with deepMap

### LINKED ISSUE #5839: Property 'message' does not exist on type 'DeepMap<Date, FieldError>' when the field is nullable
**Describe the bug**
When using `Date | null` type the error field is not inferred correctly, is inferred as `Date` not `FieldError`

```jsx
interface FormData {
  name: string;
  birthdate: Date | null;
}
// ...
const { formState } = useForm<FormData>();
// ...
<small role="alert">{formState.errors.birthdate.message}</small>
// Property 'message' does not exist on type 'DeepMap<Date, FieldError>'.
```

image

**To Reproduce**

1. Go to https://codesandbox.io/s/keen-shamir-2zqxn
2. Open the file Form.tsx or FormWithZod.tsx
3. Go to [line 76 in Form.tsx](https://codesandbox.io/s/keen-shamir-2zqxn?file=/src/Form.tsx:2097-2131) or [line 50 in FormWithZod.tsx](https://codesandbox.io/s/keen-shamir-2zqxn?file=/src/FormWithZod.tsx:1479-1513)
4. See the Typescript error

**Codesandbox link (Required)**
https://codesandbox.io/s/keen-shamir-2zqxn

**Expected behavior**
Infer the type of the error as `FieldError` because property `message` actually exists and it isn't a date object

**Screenshots**
image

**Desktop (please complete the following information):**

- OS: GNU/Linux (Manjaro)
- Browser Firefox
- Version 89

**Additional context**
Maybe this is related to #5808

### PR DESCRIPTION
**Pull request by bluebill1049**
close #5839

### CODE REVIEW

File: src/types/utils.ts [hunk 1]
```diff
@@ -14,6 +14,8 @@ export type EmptyObject = { [K in string | number]: never };
 
 export type NonUndefined<T> = T extends undefined ? never : T;
 
+export type NonNullOrUndefined<T> = T extends undefined | null ? never : T;
+
```
Comment (kotarella1110) [inline src/types/utils.ts:18]: You can remove this line 👍🏻

File: src/types/utils.ts [hunk 2]
```diff
@@ -35,7 +37,7 @@ export type IsAny<T> = boolean extends (T extends never ? true : false)
 export type DeepMap<T, TValue> = {
   [K in keyof T]?: IsAny<T[K]> extends true
     ? any
-    : NonUndefined<T[K]> extends NestedValue | Date | FileList | File
+    : NonNullOrUndefined<T[K]> extends NestedValue | Date | FileList | File
```
Comment (kotarella1110) [inline src/types/utils.ts:40]:
```suggestion
    : NonNullable<T[K]> extends NestedValue | Date | FileList | File
```

**Review by kotarella1110 — CHANGES_REQUESTED** [review]
@bluebill1049 You can use [`NonNullable`](https://www.typescriptlang.org/docs/handbook/utility-types.html#nonnullabletype) type.

**Review by kotarella1110 — APPROVED** [review]
LGTM🎉
