### PR TITLE
fix #2257 nested field array remove error

### LINKED ISSUE #2257: [useFieldArray] validation does not work properly on append/remove
**Describe the bug**
When using `useFieldArray` and upon removal of one or many fields, the existing errors are not being removed from the validation.

**To Reproduce**
1. Go to the sandbox link below and change the number value to -1. You will see that this field has an error.
2. Delete this input by clicking on the "DELETE" button.
3. Add a new field by clicking on the "APPEND NESTED" button.

You will see that the error is still there.
Same test can be done with several fields in error.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-gy89e?from-embed

**Expected behavior**
The form should revalidate when an item is removed from the fields array and get rid of the errors that point to non existing items.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version 83.0.4103.116 (Official Build) (64-bit)

**Additional context**
Tested in v5.7.2 and v6.0.6
For more details, I also explained the issue there: https://spectrum.chat/react-hook-form/help/how-to-trigger-validation-on-append-remove~c8b29049-01f1-4abf-998c-26af08b9c133?m=MTU5NDY0NzU4MjMxNA==

### PR DESCRIPTION
**Pull request by bluebill1049**
fix #2257

hey @keiya01 would you like to take over this ticket, both implementation, and tests? I think what i did fix the problem, maybe you can take a deep look at it. if you busy, i am happy to continue the work too.

### CODE REVIEW

**Comment by keiya01** [comment]
@bluebill1049 Sure. I will check tomorrow :)

File: src/useFieldArray.ts [hunk 1]
```diff
@@ -236,12 +238,14 @@ export const useFieldArray = <
...
+      set(
+        errorsRef.current,
+        name,
+        removeArrayAt(get(errorsRef.current, name), index),
       );
-      if (!unique(errorsRef.current[name]).length) {
-        delete errorsRef.current[name];
+
+      if (!unique(get(errorsRef.current, name, [])).length) {
+        unset(errorsRef.current, name);
```
Comment (keiya01) [inline src/useFieldArray.ts:248]: LGTM :)

**Review by keiya01 — APPROVED** [review]

**Comment by bluebill1049** [comment]
Awesome! thanks very much @keiya01
