### PR TITLE
fix #3450 append focus index

### LINKED ISSUE #3450: The last thing added when appending is not in focus
**Describe the bug**

**To Reproduce**

1. Go to 'https://codesandbox.io/s/react-hook-form-usefieldarray-vy8fv'
2. Click on 'APPEND'
3. See the items in focus.

**Expected behavior**
The focus needs to be on the last item added.  
This sample is working fine.

But I don't know what the difference is.

https://codesandbox.io/s/react-hook-form-usefieldarray-focus-last-added-forked-7dury?file=/src/fieldArray.js

**Screenshots**

image

**Desktop (please complete the following information):**

- OS: [Windows 10]
- Browser [chrome]
- Version [ 86.0.4240.193（Official Build） （64bit）]

### PR DESCRIPTION
**Pull request by bluebill1049**

### CODE REVIEW

File: cypress/integration/useFieldArray.ts [hunk 1]
```diff
@@ -100,10 +100,10 @@ describe('useFieldArray', () => {
       expect(JSON.parse($state.text())).to.be.deep.equal({}),
     );
 
-    cy.get('#renderCount').contains('37');
+    cy.get('#renderCount').contains('38');
   });
 
-  it('should behaviour correctly with defaultValue', () => {
+  it.only('should behaviour correctly with defaultValue', () => {
```
Comment (ghostd) [inline cypress/integration/useFieldArray.ts:106]: @bluebill1049 

Do we really want to keep this `only`?

Regards

Comment (bluebill1049) [reply cypress/integration/useFieldArray.ts:106]: oh wow... oops want to send a PR to correct this? since you found this out... my bad.

Comment (ghostd) [reply cypress/integration/useFieldArray.ts:106]: #3456
