### PR TITLE
fix setValue`s definition react-hook-form#3007

### LINKED ISSUE #3007: Typing issue: setValue accepts null or undefined unexpectedly
**Describe the bug**
Type definition of `setValue` is not respect to non-null, non-undefined definitions of `TFieldValues`

**To Reproduce**

1. define `TFieldValues` type, with nullable property and optional property
2. give generic parameter to `useForm<TFieldValues>`
3. use `setValue` with an each keys
4. run-time error is now possible

```ts

type FormValues = {
  simple: string;
  undefinedable: number | undefined;
  nullable: string | null;
  optional?: boolean;
};

const { setValue, getValues, handleSubmit, control } = useForm<FormValues>();

// all of these are not reported
setValue("simple", null);
setValue("undefinedable", null);
setValue("nullable", undefined);
setValue("optional", null);
```

**Codesandbox link (Required)**

since v6.8.3 https://codesandbox.io/s/funny-margulis-mkxp7?file=/src/App.tsx

**Expected behavior**

```ts
// all of these are reported
setValue("simple", null);
setValue("undefinedable", null);
setValue("nullable", undefined);
setValue("optional", null);
```

**Screenshots**

**Desktop (please complete the following information):**

(type definition issue)

**Smartphone (please complete the following information):**

(type definition issue)

TypeScript v4.0.3

**Additional context**

FYI: until v6.8.2 https://codesandbox.io/s/quizzical-snow-e2fxz?file=/src/App.tsx
This behavior is related to https://github.com/react-hook-form/react-hook-form/discussions/2915 , and fixed in https://github.com/react-hook-form/react-hook-form/pull/2924, but this fix causes current behavior.

### PR DESCRIPTION
**Pull request by berlysia**
resolves #3007 , if it helps

### CODE REVIEW

File: src/types/form.ts [hunk 1]
```diff
@@ -223,12 +218,9 @@ export type UseFormMethods<TFieldValues extends FieldValues = FieldValues> = {
     TFieldValue extends TFieldValues[TFieldName]
   >(
     name: TFieldName,
-    value:
-      | (NonUndefined<TFieldValue> extends NestedValue<infer U>
-          ? U
-          : UnpackNestedValue<DeepPartial<LiteralToPrimitive<TFieldValue>>>)
```
Comment (berlysia) [inline src/types/form.ts:229]: Now that we've checked that  "TFieldValue is not extends NestedValue", UnpackNestedValue seems useless

Comment (berlysia) [reply src/types/form.ts:229]: Ah, I see, NestedValue can be nested, and setValue can accepts partial object...

File: src/types/utils.ts [hunk 2]
```diff
@@ -20,15 +20,15 @@ export type LiteralUnion<T extends U, U extends Primitive> =
...
-};
+export type DeepPartial<T> = T extends Array<infer U>
+  ? Array<DeepPartial<U>>
+  : T extends ReadonlyArray<infer U>
+  ? ReadonlyArray<DeepPartial<U>>
+  : T extends Record<string, unknown>
+  ? {
+      [K in keyof T]?: DeepPartial<T[K]>;
+    }
+  : T;
```
Comment (berlysia) [inline src/types/utils.ts:31]: Previous `DeepPartial<T>` breaks `unknown` type as `{}` because `T` is implicitly assumed as something keyed object.

try the new and old one in typescript playground: https://www.typescriptlang.org/play?#code/C4TwDgpgBA8gNgEwCIQmACgQwE7AJaZwA8AKgHxQC8UA3gFBRQDaA0lHgHZQDWEIA9gDMoJALoB+AFwjWoqBAAewCBwQBnKAEFs2TCCKdBEbFACqZBoyjitOvURRosuAsXMWrUaSVnylK9SgAJQhMBH4OOBBtXX1DYzMPKxsQsIiomPtHDBx8QiJ3S0ZvX0VlVQ0QgGN+bAQiNWBsTgBzABooAFcObg5+AHcOJMYbbOc84h8WUWGvGWmAbjoAXyW6UEgoMdzXUgpqEj9ywMy4jiMTcyLrW1iHVByXfMLPbyOAytDwyOi7M4vEtcUl90r87tsnm4yLM3mUPsEIDU6g0mq0Ot1egMhkDaMw2JweHwhCIJNIIRNSLIyMtrt41ghEXAcNAahxGlAACQAOQgjQgCAAaoROhBpN08ABHEVQNQgAC2ACN+HA1oowLVgFANtAeXzBcKIERLCQhXBpXCKl0en1Bkw5AAfBFI+qNZocdpWzGDfbXR0Ym0cO2+p21F2o93o61Yiz7WiWJjc3nKfVmiCiaQcCAAN2MS2WUAAZCJTSK1tqzBwwJgqtxdcmS4byFQRO9LXX+Q2DOcElcRmZLLD-JakJhlFBHQAxPBwCAAGTwjUsNhIA5bFsC1VDKLdHv90aXuNY7C4vAEwjE0lMlertaTHYNlOmFBpxREZfA0Hnyl0cBI-HQzRyng+A5qQraBJgHAgLGhzrhorqtAeCHuqusFDoEHCdIqxgHph2HYKh4EaEqyqhBwB4kTOkGoe+mxThAiANs29CMK60jIe0liYXATIKjOGZYQqCSOtxKqWPwYD4BEhACfh45WgygicPySyMDgsTSDQAAW-AtKKUB4UJ2AdIInQtJg7Hhi0yxBjS6wfrAiAAMoQMADYkB+RqMCQ9GMQaGhwSGyIcR0kHQW0xq+QgXKYHK0CBSFkV4AxKbmuhGg+clfmpmoTCZSlMVxXIBxRQ2uX5YghVpnQsZXlWNbtqlhrwMgDzjLsX7GIQf4AXgQEgY2pUGtCFj2ZsLluQaHmQF5IhDTlRFBWGO6hVBZARd5UVVYtiWbVlTWLRVTXlVtsVps2R1lXlp1FTVzZ1TejWduSHXAV1v7-oBwF4KBl3DdCdBjdALXNi1E3uZ580ih0HFkEs5ZcgMzbg1NkP7Q2MNWXDdBAA

Comment (bluebill1049) [reply src/types/utils.ts:31]: Awesome!

**Review by bluebill1049 — APPROVED** [review]
LGTM! Thank you very much for submitting an issue and helping to resolve it.

fix verified here: https://codesandbox.io/s/nice-villani-38l18?file=/src/App.tsx:0-32

@kotarella1110 would you like to take a look at it as well?

File: src/types/utils.ts (hunk 2 above)
Comment (kotarella1110) [reply src/types/utils.ts:31]: Awesome!
I am concerned about support for lower versions of TypeScript.

https://www.typescriptlang.org/play?ts=3.6.3#code/C4TwDgpgBA8gNgEwCIQmACgQwE7AJaZwA8AKgHxQC8UA3gFBRQDaA0lHgHZQDWEIA9gDMoJALoB+AFwjWoqBAAewCBwQBnKAEFs2TCCKdBEbFACqZBoyjitOvUXjJUGHPkJFzFq1GklZ8pRV1KAAlCEwEfg44EG1dfUNjMy8rGzCIqJi4+0cUNCxcAmJPS0Zff0VlVQ0wgGN+bAQiNWBsTgBzABooAFcObg5+AHcOFMYbXOcCt2I-FlExnxl5gG46AF81ulBIKDyXQvdyKhEAquDshI4jE3NS61t4on3poo8yRd8zoJrwyOjYnYrjdkvc0n9MoCni9XG8St4vpUfqEIPVGs1Wh1un0BsNRmDaMw2JweHwhCIJNIYYdZrIyOt7r4tghUXAcNB6hwWlAACQAOQgLQgCAAaoQehBpH08ABHCVQNQgAC2ACN+HAtoowA1gFAdtABULReKIERLCQxXB5Ujqr1+oMRkw5AAfFFopotNocLp23EjCiUe6unEOjhOoNuhoezHe7H2vEWAO0SxMfmC5TGq0QUTSDgQABuxjW6ygADIRJaJVt9WYOGBMLVuIaM5XTcdqCRvrbm8LWwZrkk7uMzJZEYFbUhMMooK6AGJ4OAQAAyeBalhsJFHpxtwTqUYxXp9IYT68JrHYXF4AmEYmkpjrDab6d7JtIdKgDLKImr4GgK+UuhwCQ-DoG0Sp4PghakF2wSYBwIBJp2O4aJ6HSnqh3pbkh47BBwPSqsYp54QR2BYTBGhquq4QcKelGLnBWE-rs84QIgrYnPQjCetIGFdJYeFwGyKqLrm+EqkkroCRqlj8GA+BRIQokkTOdosoInDCmsjA4PE0g0AAFvw7SSlAxHidg3SCD07SYDxMbtOs4YMtsv6wIgADKEDAK2JC-majAkCxbEmhoyGRuivHdHBCGdOaQUIHymBKtAYWRXFeCsZm1o4RogUZcFWZqEweWZYlyVyB28WtkVJWIGV2Z0Em971o2PZZaakz5LC7j-sYhDAaBeDgZBbZVSaHwWC5uyed5Jq+ZA-kiGNhXkeF0aHlF8FkLFAXxfVq1pbt+XtattXtTVe1JdmJxndVxWXeVjUnM1j5tX21IzEQvWAQNYEQXgUG3eNHx0FN0COCcjgzT5fnLRK3S8WQaw1nywwnNDc2w8drYI-ZSN0EAA

**Review by kotarella1110 — APPROVED** [review]
LGTM! Thanks for your awesome PR!

**Comment by bluebill1049** [comment]
perhaps we should leave a note at the doc, which version we will need to support?
