### PR TITLE
#1580 Controller with render props API

### LINKED ISSUE #1580: Controller requires it's props for custom components
**Describe the bug**
When using `Controller` with a custom input component, causes the `Controller` to require the `value` and `onChange` props to be required.

**To Reproduce**
1. Open codesandbox
2. Observe the type errors

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-template-qrtco

**Expected behavior**
I would expect the typings to be smart enough to know if I have already passed the values or to know that the properties are injected.

**Additional context**
Also appears to be an issue with `<input name="test" />`

### PR DESCRIPTION
**Pull request by bluebill1049**
### 🔍Origin

This PR is led by a TS bug #1580 where required props will require to fulfill again at the `props`.

Example CSB: https://codesandbox.io/s/react-hook-form-controller-template-qrtco

```tsx
type MyInputProps = {
  value: any;
  onChange: () => void;
};

function MyInput(props: MyInputProps) {
  return <input name="FirstName" {...props} />;
}

<Controller
  as={<input name="FirstName" />} // result in TS error for required onChange and value 
  defaultValue="FirstName"
  control={control}
/>
```

-------

### ✏️Solutions

Render prop was purposed by @kotarella1110 which also lead to a discussion around shaping better API. Here are the options 

-------

**OPTION A** only support Render Props for `Controller`

**cons:** 

1. verbose for simple usage 
2. impact API consistency between `ErrorMessage` and `Controller`

**pros:**

1. consistent usage with Controller
2. less code inside lib
3. predictable result 

-------

**OPTION B** support both `as` and `render` 

**cons:** 

1. less intuitive consider providing two options: `as` vs `render`. this could lead to confusion.
2. lack of consistent usage

**pros:**

1. consistent API across `ErrorMessage` & `Controller`
2. more code inside lib
3. simple usage option, plug-in & play
4. the community seems to be keener with both options 

-------

❌ **OPTION C** `render` support render props and component

This approach having issues with good/easy `TS` support and having issue `useFieldArray` (which lead input to remount)

Screen Recording 2020-05-30 at 10 46 28 am

-------

### 📧Poll result

The above options lead us into discussion and poll on twitter. Below is a good result.

image

-------

### 📦What's next?

The plan is to release an **RC.2 version** with **option B** and waiting for the community's feedback for **2 weeks** before releasing the new V6. During the period, if users raise concerns over the new API and we will re-look at **option A** again. 

-------

### 📘Changes

- [x] Controller

Less of a breaking change for existing users, simple usage remain while still give the user the full control with render prop. Remove the following props 

- `onChange` 
- `onChangeName` 
- `onBlur`
- `onBlurName`
- `valueName`

Simple usage as below, will not be impacted:

```tsx
<Controller as={TextField} control={control} name="test" />
```

Usage involed configration and those remmoved props:

```diff
-<Controller 
-  as={CustomInput} 
-  valueName="textValue"
-  onChangeName="onTextChange"
-  control={control} 
-  name="test"  
-/>
+<Controller 
+  render={({ onChange, onBlur, value }) => (
+     <CustomInput onTextChange={onChange} onBlur={onBlur} textValue={value} />
+  )}
+  control={control} 
+  name="test"  
+/>
```

-------

- [x] ErrorMessage

change render props from `children` to `render`, usage change from the ability to use both to either. you can either use `as` or `render`. for multiple error messages, you will have to use `render`

```tsx
<ErrrorMessage errors={errors} as="p" />
<ErrrorMessage errors={errors} render={({message}) => {message}} />
```

-------

**Note:** Both `ErrorMessage` and `Controller` contains `as` and `render` props. Users should  either use `as` or `render`.

```tsx
❌<Controller as={TextField}  render={(props) => <TextField {...props} />}/>
❌<ErrorMessage as={TextField}  render={({ message }) => {message} }/>

✅<Controller as={TextField}  />
✅<Controller render={(props) => <TextField {...props} />}/>

✅<ErrorMessage as={TextField} />
✅<ErrorMessage render={({ message }) => {message} }/>
```

### CODE REVIEW

**Comment by bluebill1049** [comment]
Let me know what your guys think please, thanks for @kotarella1110's suggestion.

File: src/controller.tsx [hunk 1]
```diff
@@ -135,38 +128,39 @@ const Controller = <
...
+      !get(touchedFieldsRef.current, name)
+    ) {
+      set(touchedFieldsRef.current, name, true);
+      reRender();
+    }
+
+    if (shouldReValidateOnBlur) {
+      trigger(name);
+    }
+  };
```
Comment (kotarella1110) [inline src/controller.tsx:143]: I think you need to do the following to make the onBlur event handleable by the user:

https://codesandbox.io/s/react-hook-form-issue-1580-59soi?file=/src/src/controller.tsx:2544-3180

```ts
const commonBlurTask = () => {
  if (
    readFormStateRef.current.touched &&
    !get(touchedFieldsRef.current, name)
  ) {
    set(touchedFieldsRef.current, name, true);
    reRender();
  }

  if (shouldReValidateOnBlur) {
    trigger(name);
  }
};

function handleBlur(...args: any): void;
function handleBlur(handler: EventFunction): (...args: any) => void;
function handleBlur(handlerOrArgs: any): ((...args: any) => void) | void {
  if (typeof handlerOrArgs !== 'function') {
    commonBlurTask();
  }
  return (...args: any) => {
    handlerOrArgs(args);
    commonBlurTask();
  };
}
```

```ts
<Controller 
  name="test" 
  control={control} 
  render={({ handleChange, handleBlur, value}) => <CustomInput
      value={value}
      onChange={handleChange}
      onBlur={handleBlur((...args) => { console.log(args) })}
    />
/>
```

**Review by kotarella1110 — CHANGES_REQUESTED** [review]
I think it's better to remove `as` prop, leaving only render prop.
The reason is that if you use as prop, we need to leave `onBlur`, `onChange`, `onChangeName`, `onBlurName`, `onBlur`, `valueName` props.

```ts
export type ControllerProps<TControl extends Control = Control> = {
  name: FieldName<FieldValuesFromControl<TControl>>;
  as?: React.ReactElement;
  rules?: ValidationOptions;
  onFocus?: () => void;
  onBlur?: EventFunction;
  onChangeName?: string;
  onBlurName?: string;
  valueName?: string;
  render?: (data: {
    handleChange: EventFunction;
    handleBlur: EventFunction;
    value: any;
  }) => React.ReactElement;
  defaultValue?: unknown;
  control?: TControl;
};
```

What if we want to customize the return value? We should use `onChange` prop.

```ts
<Controller
  name="test" 
  control={control}
  as={<CustomInput />}
  onChange={(e, value) => value}
/>
```

What if the `onChange` event name is `onTextChange`? We should use `onChangeName` prop.

```ts
<Controller
  name="test" 
  control={control}
  as={<CustomInput />}
  onChange={(e, value) => value}
  onChangeName="onTextChange"
/>
```

If we have only render prop, `Controller` don't need these props.

```ts
export type ControllerProps<TControl extends Control = Control> = {
  name: FieldName<FieldValuesFromControl<TControl>>;
  rules?: ValidationOptions;
  onFocus?: () => void;
  render: (data: {
    handleChange: EventFunction;
    handleBlur: EventFunction;
    value: any;
  }) => React.ReactElement;
  defaultValue?: unknown;
  control?: TControl;
};
```

```ts
<Controller 
  name="test" 
  control={control} 
  render={({ handleChange, handleBlur, value}) => <CustomInput
      value={value}
      onTextChange={(e, value) => value}
      onBlur={handleBlur}
    />
/>
```

With render props only, it's simpler with fewer props.
RHF users can also easily predict what they are doing in the controller by passing event handlers or values ​​to the Controlled Component (`<ControlledComponent value={value} onChange={handleChange} onBlur={handleBlur} />`).

Note: I understand that removing `as` prop is a breaking change and will impact existing users.

**Comment by bluebill1049** [comment]
Thanks, @kotarella1110 I think what I refer is to use either, maybe `as` should rename to `element` like react-router. so the user still gets easy to use (if nothing onChange, onBlur, doesn't need to be renamed).

**Comment by bluebill1049** [comment]
I did a similar thing with `react-simple-animate`. users can use the following syntax
```
<Animate>Test</Animate>

<Aniamte render={} /> // if you want to customise the dom node
```

File: src/controller.tsx [hunk 2]
```diff
@@ -135,38 +128,39 @@ const Controller = <
...
+
+  const handleChange = (event: any): any =>
+    setValue(name, commonTask(event), shouldValidate());
```
[the remark this answers is not in the document]
Comment (bluebill1049) [reply src/controller.tsx:146]: Yes, you are right, please commit that change. 🙏  (to my branch)

File: src/controller.tsx (hunk 1 above)
Comment (bluebill1049) [reply src/controller.tsx:143]: we don't really worry about what's return by `onBlur`.

Comment (kotarella1110) [reply src/controller.tsx:143]: OK. If RHF users wants to do something in the blur event, they need to do the following:

```ts
<Controller 
  name="test" 
  control={control} 
  render={({ handleChange, handleBlur, value}) => <CustomInput
      value={value}
      onChange={handleChange}
      onBlur={(e) => {
        // do something here
        // console.log(e)
        handleBlur(e)
      }}
    />
/>
```

File: src/controller.tsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (kotarella1110) [reply src/controller.tsx:146]: @bluebill1049 I will fix 👍

**Comment by bluebill1049** [comment]
after @stramel 's feedback I think the following is best:

```
// Supported
<Controller name="test" control={control} render={<TextFields myUniqueProp={state} />} />
<Controller name="test" control={control} render={({onChange, onBlur, ...props}) => <TextFields handleChange={onChange} handleBlur={onBlur} {..props} />} />
```

File: src/controller.tsx (hunk 1 above)
Comment (bluebill1049) [reply src/controller.tsx:143]: yes, we should document that.

**Comment by kotarella1110** [comment]
@bluebill1049 if rename handleChange to onChange and handleBlur to onBlur, user can simplify the code.

```diff
export type ControllerProps<TControl extends Control = Control> = {
  name: FieldName<FieldValuesFromControl<TControl>>;
  rules?: ValidationOptions;
  onFocus?: () => void;
  render: (data: {
-    handleChange: EventFunction;
+   onChange: EventFunction;
-    handleBlur: EventFunction;
+   onBlur: EventFunction;
    value: any;
  }) => React.ReactElement;
  defaultValue?: unknown;
  control?: TControl;
};
```

```ts
<Controller 
  name="test" 
  control={control} 
  render={(props) => <CustomInput {...props} />
/>
```

**Comment by bluebill1049** [comment]
love it @kotarella1110!

**Comment by bluebill1049** [comment]
> after @stramel 's feedback I think the following is best:
> 
> ```
> // Supported
> <Controller name="test" control={control} render={<TextFields myUniqueProp={state} />} />
> <Controller name="test" control={control} render={({onChange, onBlur, ...props}) => <TextFields handleChange={onChange} handleBlur={onBlur} {..props} />} />
> ```

what do you think about this proposal @kotarella1110 ?

**Comment by JeromeDeLeon** [comment]
I assumed this fix the TS that's why we want to provide render props, am I right? @bluebill1049  @kotarella1110

**Comment by bluebill1049** [comment]
> I assumed this fixes the TS that's why we want to provide render props, am I right? @bluebill1049 @kotarella1110

That's the origin, but at the same time, I think this will improve the API.

**Comment by stramel** [comment]
Do we have preference on the prop name? 

`as`, `render`, `element`, `input` or other suggestions?

**Comment by JeromeDeLeon** [comment]
I agreed with all the decision of @kotarella1110 , like we should really remove `as` as this will not be necessary anymore unless there's a fix to it for TS. As for @stramel's idea, 

```jsx
<Controller name="test" control={control} render={<TextFields myUniqueProp={state} />} />

// is the same as below?

<Controller name="test" control={control} as={<TextFields myUniqueProp={state} />} />
```

Is there any reason for supporting it in `render` prop? Just asking :wink:

I've come to like this idea of `render` thing. :smile:

**Comment by bluebill1049** [comment]
> Do we have preference on the prop name?
> 
> `as`, `render`, `element`, `input` or other suggestions?

I think `render` is pretty standard for render props. probably have to change `ErrorMessage` to follow this as well.

**Comment by bluebill1049** [comment]
> I agreed with all the decision of @kotarella1110 , like we should really remove `as` as this will not be necessary anymore unless there's a fix to it for TS. As for @stramel's idea,
> 
> ```js-jsx
> <Controller name="test" control={control} render={<TextFields myUniqueProp={state} />} />
> 
> // is the same as below?
> 
> <Controller name="test" control={control} as={<TextFields myUniqueProp={state} />} />
> ```
> 
> Is there any reason for supporting it in `render` prop? Just asking 😉
> 
> I've come to like this idea of `render` thing. 😄

Yes, I agree.

what about the following option:
```
<Controller name="test" control={control} render={<TextFields myUniqueProp={state} />} />
<Controller name="test" control={control} render={({onChange, onBlur, ...props}) => <TextFields handleChange={onChange} handleBlur={onBlur} {..props} />} />
```

so if users don't require any prop wiring, they can just use slot it in without the need to render props.

**Comment by JeromeDeLeon** [comment]
I haven't seen any cases where below applies, I have only seen `render function` so far.

```jsx
<Controller name="test" control={control} render={<TextFields myUniqueProp={state} />} />
```

**Comment by JeromeDeLeon** [comment]
Though the reason is valid :) We could move it out to `element` prop like you said.

**Comment by bluebill1049** [comment]
Happy to listen everyone's thoughts, I just thought to render prop is convenient when you need to wire those onChange and value, for standard stuff `render={<TextField />}` is short and sweet. I think most people try to follow the pattern expose `value`, `onBlur` and `onChange`.

**Comment by stramel** [comment]
The main thing that I'm worried about is the typing on the element without the render props. It may have to be render props or component. That would allow it to be short and sweet.

**Comment by JeromeDeLeon** [comment]
I'm good with using `render` like what @stramel suggested. :smile:

**Comment by bluebill1049** [comment]
> The main thing that I'm worried about is the typing on the element without the render props. It may have to be render props or component. That would allow it to be short and sweet.

Yes, i agree, 

Props `render` support `renderProps` or `component` is the best, short and sweet.

**Comment by stramel** [comment]
I also like the fact this cuts a few bytes off the size.

**Comment by bluebill1049** [comment]
let me know your thoughts as well @kotarella1110 if we can all align, I will proceed with the change.

**Comment by kotarella1110** [comment]
`render={<CustomInput />}` is very simple.
But if `onChange` is required in the `CustomInput`'s props, it will cause type error.

```ts
type CustomInput = {
  onChange: (e: any) => any; // required
};
<Controller name="test" control={control} render={<CustomInput />} /> // type error
```

**Comment by bluebill1049** [comment]
> `render={<CustomInput />}` is very simple.
> But if `onChange` is required in the `CustomInput`'s props, it will cause type error.
> 
> ```ts
> type CustomInput = {
>   onChange: (e: any) => any; // required
> };
> <Controller name="test" control={control} render={<CustomInput />} /> // type error
> ```

I think if it's required, then user has the opportunity to use `renderProps`. I guess it's optional.

**Comment by bluebill1049** [comment]
I think this will tick both boxes, in terms of simplicity and type support.

**Comment by stramel** [comment]
Yeah, I was trying to come up with a solution around it but I think the only way would be to do component.

So I think everyone is in agreement?

```
// Support

render={MyInput}
render={({ onChange, onBlur, value, ...props }) => <MyInput handleChange={onChange} handleBlur={onBlur} myValue={value} {...props} customProp={state.isCustom} />}
```

**Comment by kotarella1110** [comment]
> Yeah, I was trying to come up with a solution around it but I think the only way would be to do component.
> 
> So I think everyone is in agreement?
> 
> ```
> // Support
> 
> render={MyInput}
> render={({ onChange, onBlur, value, ...props }) => <MyInput handleChange={onChange} handleBlur={onBlur} myValue={value} {...props} customProp={state.isCustom} />}
> ```

awesome! all OK!

**Comment by bluebill1049** [comment]
I will start working on it tonight, but feel free to commit to my branch. if you find the thing is missing and incorrect.

**Comment by bluebill1049** [comment]
maybe we should fix ErrorMessage as well, so the API is consistent. 

```
<ErrorMessage render={} />
```

and remove `children` and `as` props.

**Comment by kotarella1110** [comment]
> @kotarella1110 maybe we should fix ErrorMessage as well, so the API is consistent.
> 
> ```
> <ErrorMessage render={} />
> ```
> 
> and remove `children` and `as` props.

I agree with you.
This is OK?

```ts
// not support
<ErrorMessage render={CustomMessage} />
// support
<ErrorMessagee rennder={({ message }) => <CustomMessage>{message}</CustomMessage>} />
```

**Comment by bluebill1049** [comment]
yea sounds good @kotarella1110 consistent API is great.

**Comment by kotarella1110** [comment]
I will fix ErrorMessage component 👍

File: src/controller.tsx [hunk 3]
```diff
@@ -152,15 +146,15 @@ const Controller = <
...
-    ? React.isValidElement(as)
-      ? React.cloneElement(as, props)
-      : React.createElement(as as string, props)
-    : render({
-        value,
-        handleChange,
-        handleBlur,
-      });
+  return isReactComponentClass(InnerComponent) ? (
+    <InnerComponent {...props} />
```
Comment (bluebill1049) [inline src/controller.tsx:150]: we can't use `clone`?

File: src/controller.tsx [hunk 4]
```diff
@@ -152,15 +146,15 @@ const Controller = <
...
-  return as
-    ? React.isValidElement(as)
-      ? React.cloneElement(as, props)
-      : React.createElement(as as string, props)
-    : render({
-        value,
-        handleChange,
-        handleBlur,
-      });
+  return isReactComponentClass(InnerComponent) ? (
```
Comment (bluebill1049) [inline src/controller.tsx:149]: do we need this check? or `isValidElement` is good enough?

File: src/utils/isReactComponentClass.ts [hunk 5]
```diff
@@ -0,0 +1,7 @@
+import React from 'react';
+
+export default (component: any): component is React.ComponentClass<any> =>
```
Comment (bluebill1049) [inline src/utils/isReactComponentClass.ts:3]: will `isValidElement` enough for the check instead of this utility function?

File: src/controller.tsx (hunk 4 above)
Comment (bluebill1049) [reply src/controller.tsx:142]: hmmm i see <Test /> will return false. is there any better way then the function below?

Comment (bluebill1049) [reply src/controller.tsx:157]: https://codesandbox.io/s/unruffled-mahavira-x5hnw?file=/src/App.js it doesn't really work.

Comment (kotarella1110) [reply src/controller.tsx:157]: `isReactComponentClass` is is a function that validates a class component.

```ts
class ClassComponent extends React.Component {
  render() {
    return <div />;
  }
}

const FunctionComponent = () => {
  return <div />;
};

isReactComponentClass(ClassComponent) // true
isReactComponentClass(FunctionComponent) // true
```

https://codesandbox.io/s/silly-chaplygin-tb74k

Comment (bluebill1049) [reply src/controller.tsx:157]: sorry, why are we testing for Class component?

File: src/controller.tsx [hunk 6]
```diff
@@ -135,38 +122,54 @@ const Controller = <
...
+      );
+  }
+
+  return isReactComponentClass(InnerComponent) ? (
+    <InnerComponent
+      {...{
+        onChange,
+        onBlur,
+        ...{ [isCheckboxInput ? 'checked' : VALUE]: value },
+        ...rest,
```
Comment (kotarella1110) [inline src/controller.tsx:163]: I don't think rest props are unnecessary. I think users should use render prop if they want to pass custom props to `ControlledComponent`.

```ts
type CustomInputProps = {
  custom: string;
  onChange?: (...args: any[]) => any;
  onBlur?: (...args: any[]) => any;
  value?: string;
}

<Controller 
  name="test" 
  control={control} 
  render={(props) => <CustomInput {...props} custom="custom" />
/>
```

Comment (bluebill1049) [reply src/controller.tsx:163]: what if user just wants to add a className?

`<Controller className="test" name="test" control={control} />`

File: src/controller.tsx (hunk 4 above)
Comment (kotarella1110) [reply src/controller.tsx:157]: `React.ComponentType` is union of `React.ComponentClass` and `React.FunctionComponent`.


```ts
type React.ComponentType<P = {}> = React.ComponentClass<P, any> | React.FunctionComponent<P>
```

The Controlled Input may also be a Class Component.

Comment (bluebill1049) [reply src/controller.tsx:157]: but the check right now said if it's a class component do <Xxxx /> otherwise render props?

File: src/controller.tsx (hunk 6 above)
Comment (JeromeDeLeon) [reply src/controller.tsx:163]: Like what @stramel said
> ```
> // Support
> 
> render={MyInput}
> render={({ onChange, onBlur, value, ...props }) => <MyInput handleChange={onChange} handleBlur={onBlur} myValue={value} {...props} customProp={state.isCustom} />}
> ```

If we would support passing `MyInput` directly then we need `rest` but for me since we now have render props, I will leave everything to the `InnerComponent` instead of passing it to `Controller`. Just my opinion though.

File: src/controller.tsx (hunk 4 above)
Comment (kotarella1110) [reply src/controller.tsx:157]: @bluebill1049 Yes. Just as you said.

File: src/controller.tsx (hunk 6 above)
Comment (kotarella1110) [reply src/controller.tsx:163]: I think user should do the following:

```ts
<Controller 
  name="test" 
  control={control} 
  render={(props) => <CustomInput {...props} className="test" />
/>
```

File: src/controller.tsx (hunk 4 above)
Comment (JeromeDeLeon) [reply src/controller.tsx:157]: Couldn't we just check if it's a component, because either way they are both component that can be rendered on screen right?

File: src/controller.tsx (hunk 6 above)
Comment (bluebill1049) [reply src/controller.tsx:163]: hmmm, I think mixed with `Component ` with `render props` sounds good on paper, but during implementation is not great, especially with the `component` type check that @kotarella1110 introduced. I think maybe we should make a decision on the following

1. use two props `as` or `render`
con: two props
pro: we still have good DX with `as` when a component is simple

2. use render props only
con: lost the DX with a simple component
prop:  less headache and easy to implement.

File: src/controller.tsx (hunk 4 above)
Comment (bluebill1049) [reply src/controller.tsx:157]: yes, @JeromeDeLeon that's what I am after here, we shouldn't differentiate Class vs Functional component. but after reading through StackOverflow, 

it's not a simple check. https://stackoverflow.com/questions/33199959/how-to-detect-a-react-component-vs-a-react-element

File: src/controller.tsx (hunk 6 above)
Comment (kotarella1110) [reply src/controller.tsx:163]: I agree with the second proposal.

Comment (bluebill1049) [reply src/controller.tsx:163]: How about this plan? Let's go all the way with `render props` first. Then worry about component after. at least we nail one goal first before the other.

Comment (bluebill1049) [reply src/controller.tsx:163]: if people miss `as` we can introduce it again and it won't be **type** safe.

Comment (bluebill1049) [reply src/controller.tsx:163]: make sure you do a code review on this PR when it's ready @JeromeDeLeon. this is your territory that we are messing around 👍

Comment (bluebill1049) [reply src/controller.tsx]: sorry for taking the wrong direction and wasting your effort @kotarella1110 😭

Comment (kotarella1110) [reply src/controller.tsx]: @bluebill1049 do not worry 👍

File: src/utils/isReactComponentClass.ts (hunk 5 above)
Comment (JeromeDeLeon) [inline src/utils/isReactComponentClass.ts]: Shouldn't be just return a boolean? I just tried it with codesandbox and it returns an object.

Comment (bluebill1049) [reply src/utils/isReactComponentClass.ts]: this is removed :)

File: src/controller.tsx (hunk 6 above)
Comment (JeromeDeLeon) [reply src/controller.tsx]: Will do. Later tonight.

File: src/controller.tsx (hunk 4 above)
Comment (JeromeDeLeon) [reply src/controller.tsx]: Yes, I also read that one and think that it's not as simple as it is.

File: src/controller.tsx [hunk 7]
```diff
@@ -135,38 +121,40 @@ const Controller = <
...
+  ): (...event: any[]) => void;
+  function onChange(
+    ...callbackOrEvent: any[]
+  ): ((...event: any[]) => void) | void {
+    const [firstArg] = callbackOrEvent;
+
+    return isFunction(firstArg)
+      ? (event: any) =>
+          setValue(name, commonTask(firstArg(event)), shouldValidate())
+      : setValue(name, commonTask(...callbackOrEvent), shouldValidate());
```
Comment (bluebill1049) [inline src/controller.tsx:150]: @kotarella1110 can you review what I did?

Comment (kotarella1110) [reply src/controller.tsx]: @bluebill1049 wow! greate! Thanks.
Does `getInputValue` inside `commonTask` work correctly if this is multiple event args?

Comment (kotarella1110) [reply src/controller.tsx]: I missed this commit (https://github.com/react-hook-form/react-hook-form/pull/1711/commits/a93e713e9f1f870ca5d6c3821d7b31c89b961772). I think it works correctly 💯

**Comment by bluebill1049** [comment]
create another PR to support both 
`as` and `render` consider we are already doing with `ErrorMessage`. so we can keep API consistent with support `as` and `render` obviously `as` will have an issue with required type, so use `render props` to avoid issues like that, however, we still can provide flexibility to users. This also leads to a minimum change to ErrorMessage as well, the only thing to change is `children` to `render`.

**Comment by bluebill1049** [comment]
Lost a few hrs of sleep last night to think over this API, here are my thoughts and feel free to raise your objection.

This PR is trigger by `Type` related issue which cause by `as` which makes sense to provider solution with this with render prop, but it doesn't/shouldn't mean we should kill the flexible with `as`. 

--------

- `as` will be remained for simple usage assume most of the external component does follow standard component, which is exposed with `onChange` and `value` as optional not required type.
- `onChange, onChangeName, onBlur, onBlurName, valueName` will be remmoved
- render props to support custom methods to support those methods have been removed.

**Comment by JeromeDeLeon** [comment]
Could you show a sample snippet of using `as` and `render` props?

**Comment by bluebill1049** [comment]
> Could you show a sample snippet of using `as` and `render` props?

They don't work together, just like ErrorMessage. you use either `as` or `render`

```tsx
<Controller as={TextField} control={control} name="test" />
```

or

```tsx
<Controller render={props => <TextField {...props} />} control={control} name="test" />
```

**Comment by JeromeDeLeon** [comment]
I understand your decision and seems valid for me. The only difference I could see is customization. `as` prop works out of the box while keeping the simplicity to use and `render` prop is for customization but I could only see myself using the `as` prop as I don't have any use cases for customization right now aside when `onChangeName` or `valueName` is different and even the introduction of below snippet, I still prefer to write it like what you did above.

```jsx
<Controller as={<CustomInput />} />

// I still prefer it this way,
<Controller as={CustomInput} />
```

**Comment by bluebill1049** [comment]
> I understand your decision and seems valid for me. The only difference I could see is customization. `as` prop works out of the box while keeping the simplicity to use and `render` prop is for customization but I could only see myself using the `as` prop as I don't have any use cases for customization right now aside when `onChangeName` or `valueName` is different and even the introduction of below snippet, I still prefer to write it like what you did above.
> 
> ```js-jsx
> <Controller as={<CustomInput />} />
> 
> // I still prefer it this way,
> <Controller as={CustomInput} />
> ```

For this part we will keep API as what we have today:

```
// all valid
<Controller as={<CustomInput />} />
<Controller as={"input"} />
<Controller as={CustomInput} />
```

**Comment by stramel** [comment]
Wait since this is for v6, why are we not removing the `as`?

**Comment by bluebill1049** [comment]
> Wait since this is for v6, why are we not removing the `as`?

because of its simplicity as I have demonstrated above. ErrorMessage shares the same usage with `as` and `render`.

**Comment by stramel** [comment]
Why do we need both props? That will just result in a confusing API. The simplicity can still remain. The single prop can cover all cases.

Personally, I very much dislike the string use-case. I don't really see a benefit to it.

**Comment by bluebill1049** [comment]
> Why do we need both props? That will just result in a confusing API. The simplicity can still remain since the single prop can cover all cases.
> 
> Personally, I very much dislike the string use-case. I don't really see a benefit to it.

I understand your concern with `as` with string, and so does is an optional and personal preference thing.

**Comment by JeromeDeLeon** [comment]
> Why do we need both props? That will just result in a confusing API. The simplicity can still remain since the single prop can cover all cases.
> 
> Personally, I very much dislike the string use-case. I don't really see a benefit to it.

I see, I do think string-case is invalid because `Controller` is for Custom Component that doesn't support ref and string-case like `input`, `select`, `textarea` doesn't need `Controller` at all at makes thing more complicated. We could omit the support for string-case here or DOMElement.

**Comment by bluebill1049** [comment]
I am also looking at the API at the wholist point of view.

remove `as` means we need to remove `as` at `ErrorMessage`, and I still believe as is the simplest way to render an error message at `ErrorMessage`, some users may prefer `as` with its simplicity and some will have to force to use `renderProps` for the sake of custom event name. I think give people the option is not the bad thing, it shouldn't create too much confusion for the API. 

it's simple as using `as` if you don't need to configure anything, otherwise use render props to wire it up yourself.

**Comment by kotarella1110** [comment]
> `render={<CustomInput />}` is very simple.
> But if `onChange` is required in the `CustomInput`'s props, it will cause type error.
> 
> ```ts
> type CustomInput = {
>   onChange: (e: any) => any; // required
> };
> <Controller name="test" control={control} render={<CustomInput />} /> // type error
> ```

@bluebill1049 If the above issue occurs, is this solution users need to use `React.ComponetType` or render prop as below?

```ts
<Controller name="test" control={control} as={CustomInput} />
```

or

```ts
<Controller name="test" control={control} render={props => <CustomInput {...props} />} />
```

**Comment by bluebill1049** [comment]
> > `render={<CustomInput />}` is very simple.
> > But if `onChange` is required in the `CustomInput`'s props, it will cause type error.
> > ```ts
> > type CustomInput = {
> >   onChange: (e: any) => any; // required
> > };
> > <Controller name="test" control={control} render={<CustomInput />} /> // type error
> > ```
> 
> @bluebill1049 If the above issue occurs, is this solution users need to use `React.ComponetType` or render prop as below?
> 
> ```ts
> <Controller name="test" control={control} as={CustomInput} />
> ```
> 
> or
> 
> ```ts
> <Controller name="test" control={control} render={props => <CustomInput {...props} />} />
> ```

Simple usage stays with `as`:

```
<ErrorMessage as={<StyledParagraph />} errors={errors} />
<Controller as={<TextField} />} name="test" control={control} />
```

Type error or custom node structure use render props

```
<ErrorMessage errors={errors} render={({ message }) => {
  <div><span className="error">{message}</span></div>
}} />
<Controller 
  name="test" 
  control={control} 
  render={props => <div><CustomInput {...props} /></div>}
/>
````

**Comment by kotarella1110** [comment]
@bluebill1049 Do you not support `React.ComponetType` and `keyof JSX.IntrinsicElements`?

```ts
// not support?
<Controller as={TextField} name="test" control={control} />
```

**Comment by bluebill1049** [comment]
> @bluebill1049 Do you not support `React.ComponetType` and `keyof JSX.IntrinsicElements`?
> 
> ```ts
> // not support?
> <Controller as={TextField} name="test" control={control} />
> ```
> 
> Also, do you support rest props?
> 
> ```ts
> <Controller as={<TextField />} name="test" control={control} custom="custom" />
> ```

What you and @JeromeDeLeon have done with the Controller will stay as it is for today (a little less breaking change for the existing users), except we will only remove `onChangeName`, `onBlurName`, `valueName` and replaced with render props approach.

**Comment by stramel** [comment]
I still really don't like the idea of offering both `as` and `render`. The API is not intuitive. What happens when I pass both props?

**Comment by bluebill1049** [comment]
> I still really don't like the idea of offering both `as` and `render`. The API is not intuitive. What happens when I pass both props?

That's what we have inside ErrorMessage:

```
  return InnerComponent ? (
    React.isValidElement(InnerComponent) ? (
      React.cloneElement(InnerComponent, props)
    ) : (
      React.createElement(InnerComponent as string, props)
    )
  ) : (
    <React.Fragment {...props} />
  );
```

**Comment by bluebill1049** [comment]
In fact, `as` is used by `styled-component` and `chakra UI` as well.

Take an example here:
 
```
<Box as="button" rounded="md" bg="tomato" color="white" px={4} h={8} />
```

<Box as="button" rounded="md" bg="tomato" color="white" px={4} h={8}>
  {YourContent}
</Box>
```

**Comment by bluebill1049** [comment]
This Component is been there for a while: I didn't hear people complain about the usage just yet: https://react-hook-form.com/api#ErrorMessage

**Comment by bluebill1049** [comment]
Look away from Controller for a sec, what about ErrorMessage

```
<ErrorMessage as={StyledError} name="Test" />

<ErrorMessage render={({ message }) => <StyledError>{message}</StyledError>} name="Test" /> //how inconvient it is for something simple
```

**Comment by bluebill1049** [comment]
shared a vote on twitter: https://twitter.com/HookForm/status/1266240189195669505 decision will be made by tmr after the vote.

**Comment by bluebill1049** [comment]
If we can easily diff between `callback` and `component` with `render`, then it's good to move ahead, but reality the check is not great and pretty.

**Comment by stramel** [comment]
Is there a reason that we need to check? Can't we just call the function using `createElement`? In reality, it's just an inline component...

**Comment by bluebill1049** [comment]
> Is there a reason that we need to check? Can't we just call the function using `createElement`? In reality, it's just an inline component...

can you elaborate on this? 
```
render={() => {}}
render={Test}
```
how can we know which one to use React.createElement()?

**Comment by stramel** [comment]
Isn't all of this essentially equal?

```
const Test = () => <input />
render={Test}
```

vs

```
render={() => <input />}
```

It's essentially an inline component.

**Comment by bluebill1049** [comment]
> Isn't all of this essentially equal?
> 
> ```
> const Test = () => <input />
> render={Test}
> ```
> 
> vs
> 
> ```
> render={() => <input />}
> ```
> 
> It's essentially an inline component.

where are all the `props`?

**Comment by bluebill1049** [comment]
> Isn't all of this essentially equal?
> 
> ```
> const Test = () => <input />
> render={Test}
> ```
> 
> vs
> 
> ```
> render={() => <input />}
> ```
> 
> It's essentially an inline component.

I think you are right, we can always just do `React.creatElement('xxx', props)`, it doesn't need a check.

**Comment by JeromeDeLeon** [comment]
[Codesandbox](https://codesandbox.io/s/suspicious-wing-d9n1f?file=/src/App.js) I tried it, @stramel was right. I didn't know that.

**Comment by stramel** [comment]
It's late here but I will post some more detailed thoughts in the morning

**Comment by JeromeDeLeon** [comment]
Thanks @stramel I learned new stuff today :confetti_ball:

**Comment by bluebill1049** [comment]
> It's late here but I will post some more detailed thoughts in the morning

I didn't proceeds with render for all because all the `React.prototype` check. This is great! my god wasted almost 1 day discuss this...

**Comment by JeromeDeLeon** [comment]
I must say this discussion is worthwhile. I enjoyed being part of this.

**Comment by bluebill1049** [comment]
i guess this is what we after?

```
return React.createElement(render, {
    onChange,
    onBlur,
    value,
});
```

**Comment by JeromeDeLeon** [comment]
We could even passed the `name` and `controller`

**Comment by bluebill1049** [comment]
> We could even passed the `name` and `controller`

what do you mean?

**Comment by JeromeDeLeon** [comment]
I mean below snippet. I saw that you passed the `control` and `name` instead of putting it inside `props` or that doesn't make sense?

> ```tsx
> <Controller render={props => <TextField {...props} />} control={control} name="test" />
> ```

**Comment by bluebill1049** [comment]
> I mean below snippet. I saw that you passed the `control` and `name` instead of putting it inside `props` or that doesn't make sense?
> 
> > ```tsx
> > <Controller render={props => <TextField {...props} />} control={control} name="test" />
> > ```

Below looks right to me.
`<Controller render={props => <TextField {...props} />} control={control} name="test" />`

**Comment by bluebill1049** [comment]
ok running into the same problem again...

Screen Shot 2020-05-29 at 5 28 17 pm
Screen Shot 2020-05-29 at 5 28 09 pm

**Comment by JeromeDeLeon** [comment]
Tell me if I'm wrong, but to my understanding, `control` is only being used inside `Controller` and not the `InnerComponent`, that's why we never passed it to `props` right?

For `name`, not all Components support `name` prop like `react-select`.

For `Controller`'s use case:

```jsx
<Controller
  control={control}
  name="reactSelect"
  render={({ onChange, ...restProps }) => (
    <Select
      {...restProps}
      onChange={onChange(selected => selected)}
      options={options}
    />
  )}
/>
```

**Comment by bluebill1049** [comment]
> Tell me if I'm wrong, but to my understanding, `control` is only being used inside `Controller` and not the `InnerComponent`, that's why we never passed it to `props` right?
> 
> For `name`, not all Components support `name` prop like `react-select`.
> 
> For `Controller`'s use case:
> 
> ```js-jsx
> <Controller
>   control={control}
>   name="reactSelect"
>   render={({ onChange, ...restProps }) => (
>     <Select
>       {...restProps}
>       onChange={onChange(selected => selected)}
>       options={options}
>     />
>   )}
> />
> ```

Yes correct, control, and name is for RHF.

**Comment by bluebill1049** [comment]
I think either:

1. `renderProps` all the way or (unless someone can solve my problem above)
2. `support` both separately. 

let's see the votes tmr.

**Comment by JeromeDeLeon** [comment]
> ok running into the same problem again...
> 
> Screen Shot 2020-05-29 at 5 28 17 pm
> 
> Screen Shot 2020-05-29 at 5 28 09 pm
> 
> we still need to differentiate callback (as a component with payloads) vs react component in order to let the type work correctly, back to square one.

What file did you encounter this one? 
Screenshot from 2020-05-29 15-49-04

**Comment by bluebill1049** [comment]
> > ok running into the same problem again...
> > Screen Shot 2020-05-29 at 5 28 17 pm
> > Screen Shot 2020-05-29 at 5 28 09 pm
> > we still need to differentiate callback (as a component with payloads) vs react component in order to let the type work correctly, back to square one.
> 
> What file did you encounter that one?
> Screenshot from 2020-05-29 15-49-04

update render type to

```
render:
    | ((data: {
        onChange: {
          (...event: any[]): void;
          (callback: (...args: any[]) => any): (...event: any[]) => void;
        };
        onBlur: () => void;
        value: any;
      }) => React.ReactElement)
    | React.ComponentType<any>;
```
then you will see the error in test file with controller.

**Comment by JeromeDeLeon** [comment]
That's problematic. Couldn't we just support `render={Input}` and `render={props => <Input {...props} />}`?

**Comment by bluebill1049** [comment]
> That's problematic. Couldn't we just support `render={Input}` and `render={props => <Input {...props} />}`?

That's what I try to achieve here. :(

**Comment by JeromeDeLeon** [comment]
Any reason why you need `React.ComponentType<any>`?

**Comment by bluebill1049** [comment]
> Any reason why you need `React.ComponentType<any>`?

for this `render={Checkbox}`.

**Comment by bluebill1049** [comment]
upon some investigation `render={Test}` || `render={() => {}}`is not a good pattern to follow and TS is not going to sing happily as well.

1. `render` prop all the way
2. `render` && `as` (similar as  react-router)

will decide that tmr and move on with this API.

**Comment by bluebill1049** [comment]
also worth mentioning if we going `render` prop only, for API consistency then make sense to remove `ErrorMessage` from this lib, because `as` props should be gone as well.

1. lose some package weight
2. the component is becoming too verbose anyhow

`<ErrorMessage render={({ message }) => <p>{messge}</p>} name="test" errors={errors} />`

vs

`errors.test?.messaga`

it's almost pointless to have such a component.

**Comment by kotarella1110** [comment]
> ok running into the same problem again...
> 
> Screen Shot 2020-05-29 at 5 28 17 pm
> 
> Screen Shot 2020-05-29 at 5 28 09 pm
> 
> we still need to differentiate callback (as a component with payloads) vs react component in order to let the type work correctly, back to square one.

I will look into whether I can.

**Comment by bluebill1049** [comment]
> > ok running into the same problem again...
> > Screen Shot 2020-05-29 at 5 28 17 pm
> > Screen Shot 2020-05-29 at 5 28 09 pm
> > we still need to differentiate callback (as a component with payloads) vs react component in order to let the type work correctly, back to square one.
> 
> I will look into whether I can.

Thanks @kotarella1110 enjoy your Friday, let's not spending more effort on this until tmr.

**Comment by JeromeDeLeon** [comment]
I don't know Controller's solution. I looked at how `react-router` implemented their own types and seemed like they separated it with `component` and `render`. I could only passed the function component but when passing Class component, I couldn't. I'll let  @kotarella1110 or @stramel handle this. :laughing:

**Comment by bluebill1049** [comment]
> I don't know Controller's solution. I looked at how `react-router` implemented their own types and seemed like they separated it with `component` and `render`. I could only passed the function component but when passing Class component, I couldn't. I'll let @kotarella1110 or @stramel handle this. 😆

That's basically `as` and `render`.

**Comment by stramel** [comment]
@bluebill1049 You should only need `React.ComponentType<{ value: any; onBlur: () => void; onChange: (...args: any[]) => void; }>`. That should support both `TextFields` and `(props) => <TextFields {...props} />`

**Comment by bluebill1049** [comment]
> @bluebill1049 You should only need
> 
> ```tsx
> React.ComponentType<{ value: any; onBlur: () => void; onChange: (...args: any[]) => void; }>
> ```
> 
> That should support both `TextFields` and `(props) => <TextFields {...props} />`

Thanks! make sense, will give it a go tmr morning.

**Comment by JeromeDeLeon** [comment]
Is that so? I tried it out earlier with ComponentType but having a problem with 

```tsx
class Component extends Component<ControllerRenderProps, any> { }
```

**Comment by stramel** [comment]
@JeromeDeLeon I modified your CodeSandbox from earlier, everything seems to be working for me. https://codesandbox.io/s/funny-nightingale-xpvuy?file=/src/App.tsx

**Comment by bluebill1049** [comment]
Screen Shot 2020-05-30 at 9 14 29 am

let's not worry about `ComponentType` with render props, keep it as pure render props. let's see the vote result and decided what I suggest above for next.

**Comment by stramel** [comment]
The problem there is you're not converting the props. Your Checkbox component doesn't take whatever you specified.

**Comment by bluebill1049** [comment]
> The problem there is you're not converting the props. Your Checkbox component doesn't take whatever you specified.

```
<Controller
  render={TextField}
  name="TextField"
  control={control}
  rules={{ required: true }}
/>
```

MUI TextField accepts `onChange, onBlur, value`, but still cry with TS. I think this proof is better to keep render props as just render props.

Screen Shot 2020-05-30 at 10 06 36 am

**Comment by bluebill1049** [comment]
I am getting renderProp only pass the automation, and then prepare for the next step.

**Comment by stramel** [comment]
It's just a typing issue with conflicting onBlur props

**Comment by bluebill1049** [comment]
> It's just a typing issue with conflicting onBlur props

Yes, it's not compatible with `onBlur` but we probably going to have more issues like this with other libs? that's why I think keeping it as render props is actually easier right?

**Comment by bluebill1049** [comment]
> It's just a typing issue with conflicting onBlur props

FYI: I am updating all the automation app to render props for now.

**Comment by bluebill1049** [comment]
currently investigating an issue with Controller render props with useFieldArrya, somehow input lost focus... feel like mount and remount.

**Comment by bluebill1049** [comment]
Screen Recording 2020-05-30 at 10 46 28 am

**Comment by bluebill1049** [comment]
@kotarella1110 can you please update your ErrorMessage component from 'children' to 'render' as well?

**Comment by bluebill1049** [comment]
Screen Shot 2020-05-30 at 5 46 53 pm

**Comment by kotarella1110** [comment]
> @kotarella1110 can you please update your ErrorMessage component from 'children' to 'render' as well?

I will do this tomorrow.

File: src/controller.tsx [hunk 8]
```diff
@@ -135,38 +121,40 @@ const Controller = <
...
+
+    return isFunction(firstArg)
+      ? (event: any) =>
+          setValue(name, commonTask(firstArg(event)), shouldValidate())
+      : setValue(name, commonTask(callbackOrEvent), shouldValidate());
+  }
+
+  return render({
+    onChange,
+    onBlur,
```
Comment (kotarella1110) [inline src/controller.tsx:155]: Do you think that we can avoid unnecessary rendering with useCallback memo?

**Comment by bluebill1049** [comment]
> > @kotarella1110 can you please update your ErrorMessage component from 'children' to 'render' as well?
> 
> I will do this tomorrow.

nvm, I already did :) hehe just a small comment.

File: src/controller.tsx (hunk 8 above)
Comment (bluebill1049) [reply src/controller.tsx:155]: 🤔 hmmm good point.

**Comment by kotarella1110** [comment]
> > > @kotarella1110 can you please update your ErrorMessage component from 'children' to 'render' as well?
> > 
> > 
> > I will do this tomorrow.
> 
> nvm, I already did :) hehe just a small comment.

Sorry...
Reply is slow on weekends because I need to take care of my child 👶

**Comment by bluebill1049** [comment]
> > > > @kotarella1110 can you please update your ErrorMessage component from 'children' to 'render' as well?
> > > 
> > > 
> > > I will do this tomorrow.
> > 
> > 
> > nvm, I already did :) hehe just a small comment.
> 
> Sorry...
> Reply is slow on weekends because I need to take care of my child 👶

aha no worries @kotarella1110 didn't know you are a daddy! hahaha, take care little Kotaro. ❤️

**Comment by kotarella1110** [comment]
> > > > > @kotarella1110 can you please update your ErrorMessage component from 'children' to 'render' as well?
> > > > 
> > > > 
> > > > I will do this tomorrow.
> > > 
> > > 
> > > nvm, I already did :) hehe just a small comment.
> > 
> > 
> > Sorry...
> > Reply is slow on weekends because I need to take care of my child 👶
> 
> aha no worries @kotarella1110 didn't know you are a daddy! hahaha, take care little Kotaro. ❤️

hahaha I'm a daddy. My child was born when I joined the React Hook Form 💚

**Comment by JeromeDeLeon** [comment]
Wow! That was great! Congratulations!! :confetti_ball:

**Comment by kotarella1110** [comment]
Thank you very much @JeromeDeLeon 💚

**Comment by bluebill1049** [comment]
> > > > > > @kotarella1110 can you please update your ErrorMessage component from 'children' to 'render' as well?
> > > > > 
> > > > > 
> > > > > I will do this tomorrow.
> > > > 
> > > > 
> > > > nvm, I already did :) hehe just a small comment.
> > > 
> > > 
> > > Sorry...
> > > Reply is slow on weekends because I need to take care of my child 👶
> > 
> > 
> > aha no worries @kotarella1110 didn't know you are a daddy! hahaha, take care little Kotaro. ❤️
> 
> hahaha I'm a daddy. My baby was born when I joined React Hook Form team 💚

Congrats! happy daddy! 👨‍👩‍👦

**Comment by kotarella1110** [comment]
Thanks @bluebill1049 💚 
I raise babies (My Baby and RHF) with care 👨‍👧

**Comment by bluebill1049** [comment]
> Thanks @bluebill1049 💚
> I raise babies (My Baby and RHF) with care 👨‍👧

hahaha sounds funny 4 dads... (1 dad left, he is a good dad as well, his name is Barry) RHF is like a little baby, it's growing each day with our cares!

File: src/controller.tsx (hunk 8 above)
Comment (bluebill1049) [reply src/controller.tsx:164]: I did try `useCallback`, but it caught issue during automation test... and I didn't investigate further, feel free to take a look if you have time.

File: cypress/integration/controller.ts [hunk 9]
```diff
@@ -11,16 +11,16 @@ context('controller basic form validation', () => {
...
     cy.get('#input-textField input').type('test');
     cy.get('#input-select > div > div').click();
     cy.get('.MuiPopover-root ul > li:first-child').click();
     cy.get('#input-switch input').click();
     cy.get('#input-ReactSelect > div').click();
     cy.get('#input-ReactSelect > div > div').eq(1).click();
 
-    cy.get('p').should('have.length', 2);
-    cy.get('#renderCount').contains('8');
+    cy.get('.container > p').should('have.length', 6);
```
Comment (JeromeDeLeon) [inline cypress/integration/controller.ts:22]: The reason why it failed before was because we're getting all P tags. To solve that, get only the P tags under `.container`.

File: src/controller.tsx [hunk 10]
```diff
@@ -135,38 +129,56 @@ const Controller = <
...
+  ): ((...event: any[]) => void) | void {
+    const [firstArg] = callbackOrEvent;
+
+    return isFunction(firstArg)
+      ? (event: any) =>
+          setValue(name, commonTask(firstArg(event)), shouldValidate())
+      : setValue(name, commonTask(callbackOrEvent), shouldValidate());
+  }
+
+  const handlerProps = {
```
Comment (JeromeDeLeon) [inline src/controller.tsx:161]: I hoisted it above to avoid `conditional memoizing` rule of hooks.

File: cypress/integration/controller.ts [hunk 11]
```diff
@@ -11,16 +11,16 @@ context('controller basic form validation', () => {
...
+    cy.get('#renderCount').contains('2');
   });
 
   it('should validate the form with onBlur mode and reset the form', () => {
```
Comment (JeromeDeLeon) [inline cypress/integration/controller.ts:26]: Here's a sample of test name where `reset` button didn't get called even though it was mentioned.

File: cypress/integration/controller.ts (hunk 9 above)
Comment (bluebill1049) [reply cypress/integration/controller.ts:22]: awesome stuff @JeromeDeLeon thank you

File: cypress/integration/controller.ts (hunk 11 above)
Comment (bluebill1049) [reply cypress/integration/controller.ts:26]: thanks @JeromeDeLeon

Comment (JeromeDeLeon) [reply cypress/integration/controller.ts:26]: I will patch it together with providing types for `cy` for code review. :smile:

File: src/controller.tsx [hunk 12]
```diff
@@ -135,38 +129,56 @@ const Controller = <
...
 
-      if (shouldReValidateOnBlur) {
-        trigger(name);
-      }
-    },
-    ...{ [valueName || (isCheckboxInput ? 'checked' : VALUE)]: value },
+  function onChange(...event: any[]): void;
+  function onChange(
+    callback: (...args: any[]) => any,
+  ): (...event: any[]) => void;
```
Comment (kotarella1110) [inline src/controller.tsx:149]: I have improved it possible to customize the return value to match the existing API, but this may not be necessary for render props.
I think we can remove it to keep the API simple, what do you think?

```ts
<Controller 
  render={({ onChange, ...props }) => (
    <CustomInput
      {...props}
      onChange={(e) => {
        const customValue = custom(e.target.value);
        onChange(customValue);
      }}
    />
  )}
  control={control} 
  name="test"  
/>
```

Comment (bluebill1049) [reply src/controller.tsx:149]: sounds great.

Comment (bluebill1049) [reply src/controller.tsx]: done.

Comment (bluebill1049) [reply src/controller.tsx:149]: Do you want to do a commit on this one? I think i stuff it up by removing that overload function.

Comment (kotarella1110) [reply src/controller.tsx:149]: @bluebill1049 yes. I will fix soon!

Comment (bluebill1049) [reply src/controller.tsx:149]: ty
