### PR TITLE
fix #712 setValue path type

### LINKED ISSUE #712: Can't set value nested attributes in typescript.
**Describe the bug**
Can't set value nested attributes in typescript.
```js
setValue('name', 'test');
setValue('person.firstName', 'my name'); // <- 'person.firstName' type error
```

**To Reproduce**
1. create nest array or object form
2. setValue use in target nest property 

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-set-inputselect-value-u4u2u

**Expected behavior**
```js
type Form = { name: string, person: { firstName: string, lastName: string } };

const {setValue} = useForm<Form>();

setValue('person.firstName', 'tanmen'); //<- no error
```

**Screenshots**
スクリーンショット 2019-12-26 18 26 03

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by tanmen**
fix setValue path type in typescript

issue: #712 

### before
```js
type Form = { name: string, person: { firstName: string, lastName: string } };

const {setValue} = useForm<Form>();

setValue('person.firstName', 'tanmen'); //<- error
```

### after
```js
type Form = { name: string, person: { firstName: string, lastName: string } };

const {setValue} = useForm<Form>();

setValue('person.firstName', 'tanmen'); //<- no error
```

### CODE REVIEW

**Comment by bluebill1049** [comment]
good one 👍!  looks like some of the build failed i will take a look

File: src/types.ts [hunk 1]
```diff
@@ -4,8 +4,9 @@ export type Primitive = string | boolean | number | symbol | null | undefined;
 
 export type FieldValues = Record<string, any>;
 
-export type FieldName<FormValues extends FieldValues> = keyof FormValues &
-  string;
```
Comment (bluebill1049) [inline src/types.ts]: dont remove that & string :)

File: src/types.ts [hunk 2]
```diff
@@ -4,8 +4,9 @@ export type Primitive = string | boolean | number | symbol | null | undefined;
...
+export type FieldName<FormValues extends FieldValues> =
+  | keyof FormValues
```
Comment (bluebill1049) [inline src/types.ts]:
```suggestion
  | keyof FormValues & string
```

Comment (tanmen) [reply src/types.ts]: oh! its ok
thank you :))

**Comment by tanmen** [comment]
thank you for marge :)))
and some missed so sorry..
more like this lib, and you :)

**Comment by bluebill1049** [comment]
ha no worries @tanmen Looks like you are from JP, we have a Japanese team member as well @kotarella1110 ❤️

**Comment by tanmen** [comment]
so good :)
bud i try english :(
I so weak english..
I have to overcome English :(

**Comment by bluebill1049** [comment]
@tanmen i understand you fine :) so your English is not so "weak" haha good luck and have a good night.

**Comment by tanmen** [comment]
@bluebill1049 so thank you :)
I try create issue and contributes :)
I'll use this library and respond if I find something.
good night!
